---
- name: Install dependencies
  become: true
  apt: 
    name: ['nodejs', 'npm']
    state: latest
    update_cache: true

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
